[project]
name = "ComfyUI-Calculator"
description = "Calculator"
version = "1.0.0"
license = {file = "LICENSE"} 

[project.urls]
Repository = "https://github.com/BobRandomNumber/ComfyUI-Calculator"

[tool.comfy]
PublisherId = "bobrandomnumber"
DisplayName = "Calculator"